name: HomeAssistant
services:
  homeassistant:
    image: docker.1ms.run/homeassistant/home-assistant:stable
    container_name: homeassistant
    #network_mode: host
    ports:
      - 8123:8123
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
    restart: unless-stopped